#ifndef LIBAPI_H
#define LIBAPI_H



#if defined(DLL_IMPL) && !defined(NOT_USE_INTERNAL)
#include <btkdeclspecs.h>
#ifdef COMPILING_LIB_ANALYSISTOOLS
    #define LIB_ANALYSISTOOLS_API DLLEXPORTAPI
#else
    #define LIB_ANALYSISTOOLS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_APPINTF
    #define LIB_APPINTF_API DLLEXPORTAPI
#else
    #define LIB_APPINTF_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_CADDSUTILS
    #define LIB_CADDSUTILS_API DLLEXPORTAPI
#else
    #define LIB_CADDSUTILS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_CORESECTOOLS
    #define LIB_CORESECTOOLS_API DLLEXPORTAPI
#else
    #define LIB_CORESECTOOLS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_CORETOOLS
    #define LIB_CORETOOLS_API DLLEXPORTAPI
    #define LIB_CORETOOLS_CLASS_API DLLEXPORTAPI
#else
    #define LIB_CORETOOLS_API DLLIMPORTAPI
    #define LIB_CORETOOLS_CLASS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_CREOMDAPI
    #define LIB_CREOMDAPI_API DLLEXPORTAPI
    #define LIB_CREOMDAPI_CLASS_API DLLEXPORTAPI
#else
    #define LIB_CREOMDAPI_API DLLIMPORTAPI
    #define LIB_CREOMDAPI_CLASS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_COREUTILS
    #define LIB_COREUTILS_API DLLEXPORTAPI
    #define LIB_COREUTILS_CLASS_API DLLEXPORTAPI
#else
    #define LIB_COREUTILS_API DLLIMPORTAPI
    #define LIB_COREUTILS_CLASS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_CTX_HELP
    #define LIB_CTX_HELP_API DLLEXPORTAPI
#else
    #define LIB_CTX_HELP_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_DBKEYTOOLS
    #define LIB_DBKEYTOOLS_API DLLEXPORTAPI
#else
    #define LIB_DBKEYTOOLS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_DIMTOOLS
    #define LIB_DIMTOOLS_API DLLEXPORTAPI
#else
    #define LIB_DIMTOOLS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_DIMUTILS
    #define LIB_DIMUTILS_API DLLEXPORTAPI
#else
    #define LIB_DIMUTILS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_ANNOTTOOLS
    #define LIB_ANNOTTOOLS_API DLLEXPORTAPI
#else
    #define LIB_ANNOTTOOLS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_ASM_PREVIEW
    #define LIB_ASM_PREVIEW_API DLLEXPORTAPI
#else
    #define LIB_ASM_PREVIEW_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_BMXGRAPHTOOL
    #define LIB_BMXGRAPHTOOL_API DLLEXPORTAPI
#else
    #define LIB_BMXGRAPHTOOL_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_CFG_ASM_VERIFY_UI
    #define LIB_CFG_ASM_VERIFY_UI_API DLLEXPORTAPI
#else
    #define LIB_CFG_ASM_VERIFY_UI_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_DMA_UI
    #define LIB_DMA_UI_API DLLEXPORTAPI
#else
    #define LIB_DMA_UI_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_DRMCLIENT
    #define LIB_DRMCLIENT_API DLLEXPORTAPI
#else
    #define LIB_DRMCLIENT_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_ECAD
    #define LIB_ECAD_API DLLEXPORTAPI
#else
    #define LIB_ECAD_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_EZ_NET
    #define LIB_EZ_NET_API DLLEXPORTAPI
#else
    #define LIB_EZ_NET_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_FEAT_UI
    #define LIB_FEAT_UI_API DLLEXPORTAPI
#else
    #define LIB_FEAT_UI_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_FEMLIB
    #define LIB_FEMLIB_API DLLEXPORTAPI
#else
    #define LIB_FEMLIB_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_FREEFORM_COMBINED
    #define LIB_FREEFORM_COMBINED_API DLLEXPORTAPI
    #define LIB_FREEFORM_COMBINED_CLASS_API DLLEXPORTAPI
#else
    #define LIB_FREEFORM_COMBINED_API DLLIMPORTAPI
    #define LIB_FREEFORM_COMBINED_CLASS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_GEOMAGIC
    #define LIB_GEOMAGIC_API DLLEXPORTAPI
#else
    #define LIB_GEOMAGIC_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_GLOBALMODEL
    #define LIB_GLOBALMODEL_API DLLEXPORTAPI
#else
    #define LIB_GLOBALMODEL_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_GRMANIP
    #define LIB_GRMANIP_API DLLEXPORTAPI
#else
    #define LIB_GRMANIP_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_HELPLIB
    #define LIB_HELPLIB_API DLLEXPORTAPI
#else
    #define LIB_HELPLIB_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_INTFGEOFIX
    #define LIB_INTFGEOFIX_API DLLEXPORTAPI
#else
    #define LIB_INTFGEOFIX_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_LAYOUT_UI
    #define LIB_LAYOUT_UI_API DLLEXPORTAPI
#else
    #define LIB_LAYOUT_UI_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_LEAD_UI
    #define LIB_LEAD_UI_API DLLEXPORTAPI
#else
    #define LIB_LEAD_UI_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_LIBDCADUI
    #define LIB_LIBDCADUI_API DLLEXPORTAPI
#else
    #define LIB_LIBDCADUI_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_LIBSAVEMOD
    #define LIB_LIBSAVEMOD_API DLLEXPORTAPI
#else
    #define LIB_LIBSAVEMOD_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_LIVE_UI
    #define LIB_LIVE_UI_API DLLEXPORTAPI
#else
    #define LIB_LIVE_UI_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_MANUFACT
    #define LIB_MANUFACT_API DLLEXPORTAPI
#else
    #define LIB_MANUFACT_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_MFGGEOM
    #define LIB_MFGGEOM_API DLLEXPORTAPI
#else
    #define LIB_MFGGEOM_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_MOLD
    #define LIB_MOLD_API DLLEXPORTAPI
#else
    #define LIB_MOLD_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_MTRACK
    #define LIB_MTRACK_API DLLEXPORTAPI
#else
    #define LIB_MTRACK_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_TRYOUTFSDRV
    #define LIB_TRYOUTFSDRV_API DLLEXPORTAPI
#else
    #define LIB_TRYOUTFSDRV_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_NDPDM
    #define LIB_NDPDM_API DLLEXPORTAPI
#else
    #define LIB_NDPDM_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_NDUTIL
    #define LIB_NDUTIL_API DLLEXPORTAPI
#else
    #define LIB_NDUTIL_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_ODUIKIT
    #define LIB_ODUIKIT_API DLLEXPORTAPI
#else
    #define LIB_ODUIKIT_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PGLINTF
    #define LIB_PGLINTF_API DLLEXPORTAPI
#else
    #define LIB_PGLINTF_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PGLSTKIT
    #define LIB_PGLSTKIT_API DLLEXPORTAPI
#else
    #define LIB_PGLSTKIT_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PGLTOOLKIT
    #define LIB_PGLTOOLKIT_API DLLEXPORTAPI
#else
    #define LIB_PGLTOOLKIT_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PRO_AD
    #define LIB_PRO_AD_API DLLEXPORTAPI
#else
    #define LIB_PRO_AD_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PRO_EH
    #define LIB_PRO_EH_API DLLEXPORTAPI
#else
    #define LIB_PRO_EH_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PRO_IP
    #define LIB_PRO_IP_API DLLEXPORTAPI
#else
    #define LIB_PRO_IP_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PRO_QZ
    #define LIB_PRO_QZ_API DLLEXPORTAPI
#else
    #define LIB_PRO_QZ_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PROD_INTF
    #define LIB_PROD_INTF_API DLLEXPORTAPI
#else
    #define LIB_PROD_INTF_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PRODLG
    #define LIB_PRODLG_API DLLEXPORTAPI
#else
    #define LIB_PRODLG_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PRODLG_UI
    #define LIB_PRODLG_UI_API DLLEXPORTAPI
#else
    #define LIB_PRODLG_UI_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PROWT_BASE_BROWSER
    #define LIB_PROWT_BASE_BROWSER_API DLLEXPORTAPI
#else
    #define LIB_PROWT_BASE_BROWSER_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PROWT_MSG_UTILS
    #define LIB_PROWT_MSG_UTILS_API DLLEXPORTAPI
#else
    #define LIB_PROWT_MSG_UTILS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PROWT_OPT_UTILS
    #define LIB_PROWT_OPT_UTILS_API DLLEXPORTAPI
#else
    #define LIB_PROWT_OPT_UTILS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PROWT_SERVER_LOC_REG
    #define LIB_PROWT_SERVER_LOC_REG_API DLLEXPORTAPI
#else
    #define LIB_PROWT_SERVER_LOC_REG_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PROWT_WPPLIBS_SERVER_LOC_REG
    #define LIB_PROWT_SERVER_LOC_REG_API DLLEXPORTAPI
    #define LIB_PROWT_WPPLIBS_SERVER_LOC_REG_API DLLEXPORTAPI
    #define LIB_PROWT_WPPLIBS_SERVER_LOC_REG_CLASS_API DLLEXPORTAPI
#else
    #define LIB_PROWT_SERVER_LOC_REG_API DLLIMPORTAPI
    #define LIB_PROWT_WPPLIBS_SERVER_LOC_REG_API DLLIMPORTAPI
    #define LIB_PROWT_WPPLIBS_SERVER_LOC_REG_CLASS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PROWT_SERVER_REGISTRY
    #define LIB_PROWT_SERVER_REGISTRY_API DLLEXPORTAPI
#else
    #define LIB_PROWT_SERVER_REGISTRY_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PROWT_UI
    #define LIB_PROWT_UI_API DLLEXPORTAPI
#else
    #define LIB_PROWT_UI_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PROWTTOOLS
    #define LIB_PROWTTOOLS_API DLLEXPORTAPI
#else
    #define LIB_PROWTTOOLS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_RTALOC
    #define LIB_RTALOC_API DLLEXPORTAPI
#else
    #define LIB_RTALOC_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_SMM
    #define LIB_SMM_API DLLEXPORTAPI
#else
    #define LIB_SMM_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_SMTDESIGN
    #define LIB_SMTDESIGN_API DLLEXPORTAPI
#else
    #define LIB_SMTDESIGN_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_SUBDIVISION
    #define LIB_SUBDIVISION_API DLLEXPORTAPI
#else
    #define LIB_SUBDIVISION_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_TMC_DPR_DRM_TOOLS
    #define LIB_TMC_DPR_DRM_TOOLS_API DLLEXPORTAPI
#else
    #define LIB_TMC_DPR_DRM_TOOLS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_TMC_DPR_LIBDRM_PROE
    #define LIB_TMC_DPR_LIBDRM_PROE_API DLLEXPORTAPI
#else
    #define LIB_TMC_DPR_LIBDRM_PROE_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_TOOLKIT
    #define LIB_TOOLKIT_API DLLEXPORTAPI
#else
    #define LIB_TOOLKIT_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_TOP
    #define LIB_TOP_API DLLEXPORTAPI
#else
    #define LIB_TOP_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_UIHELPERS
    #define LIB_UIHELPERS_API DLLEXPORTAPI
#else
    #define LIB_UIHELPERS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_WPPLIBS
    #define LIB_WPPLIBS_API DLLEXPORTAPI
#else
    #define LIB_WPPLIBS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_XTOPSTART
    #define LIB_XTOPSTART_API DLLEXPORTAPI
#else
    #define LIB_XTOPSTART_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_ENTDISPTOOL
    #define LIB_ENTDISPTOOL_API DLLEXPORTAPI
#else
    #define LIB_ENTDISPTOOL_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_ENTTOOLS
    #define LIB_ENTTOOLS_API DLLEXPORTAPI
#else
    #define LIB_ENTTOOLS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_EZ_EMAIL
    #define LIB_EZ_EMAIL_API DLLEXPORTAPI
#else
    #define LIB_EZ_EMAIL_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_FCLIB
    #define LIB_FCLIB_API DLLEXPORTAPI
#else
    #define LIB_FCLIB_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_FEM_NEUTRAL
    #define LIB_FEM_NEUTRAL_API DLLEXPORTAPI
#else
    #define LIB_FEM_NEUTRAL_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_FLYBASE
    #define LIB_FLYBASE_API DLLEXPORTAPI
#else
    #define LIB_FLYBASE_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_GPLUGREAD
    #define LIB_GPLUGREAD_API DLLEXPORTAPI
#else
    #define LIB_GPLUGREAD_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_GEOMTOOLS
    #define LIB_GEOMTOOLS_API DLLEXPORTAPI
#else
    #define LIB_GEOMTOOLS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_SOLVERTOOLS
    #define LIB_SOLVERTOOLS_API DLLEXPORTAPI
#else
    #define LIB_SOLVERTOOLS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_HLREXP
    #define LIB_HLREXP_API DLLEXPORTAPI
#else
    #define LIB_HLREXP_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_IC
    #define LIB_IC_API DLLEXPORTAPI
    #define PNG_IMPEXP DLLEXPORTAPI
    #define LIB_IC_CLASS_API DLLEXPORTAPI
#else
    #define LIB_IC_API DLLIMPORTAPI
    #define PNG_IMPEXP DLLIMPORTAPI
    #define LIB_IC_CLASS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_INTFDRAW_LIB
    #define LIB_INTFDRAW_LIB_API DLLEXPORTAPI
#else
    #define LIB_INTFDRAW_LIB_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_INTFDRAWOUT_LIB
    #define LIB_INTFDRAWOUT_LIB_API DLLEXPORTAPI
#else
    #define LIB_INTFDRAWOUT_LIB_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_INTFTOOLS
    #define LIB_INTFTOOLS_API DLLEXPORTAPI
#else
    #define LIB_INTFTOOLS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_IPC_COMMS
    #define LIB_IPC_COMMS_API DLLEXPORTAPI
#else
    #define LIB_IPC_COMMS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_JPEGSOURCE
    #define LIB_JPEGSOURCE_API DLLEXPORTAPI
#else
    #define LIB_JPEGSOURCE_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_LI_IPC
    #define LIB_LI_IPC_API DLLEXPORTAPI
#else
    #define LIB_LI_IPC_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_LIBBROWSER_API
    #define LIB_LIBBROWSER_API_API DLLEXPORTAPI
#else
    #define LIB_LIBBROWSER_API_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_LIBDCADTKCLNT
    #define LIB_LIBDCADTKCLNT_API DLLEXPORTAPI
#else
    #define LIB_LIBDCADTKCLNT_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_LIBDUI
    #define LIB_LIBDUI_API DLLEXPORTAPI
#else
    #define LIB_LIBDUI_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_LIBGRMANIP
    #define LIB_LIBGRMANIP_API DLLEXPORTAPI
#else
    #define LIB_LIBGRMANIP_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_LIBHBSBIND
    #define LIB_LIBHBSBIND_API DLLEXPORTAPI
#else
    #define LIB_LIBHBSBIND_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_LIBPLPF_LOW
    #define LIB_LIBPLPF_LOW_API DLLEXPORTAPI
#else
    #define LIB_LIBPLPF_LOW_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_LIBTRLCLNT
    #define LIB_LIBTRLCLNT_API DLLEXPORTAPI
#else
    #define LIB_LIBTRLCLNT_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_LIBUI
    #define LIB_LIBUI_API DLLEXPORTAPI
#else
    #define LIB_LIBUI_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_LIBUICXX
    #define LIB_LIBUICXX_API DLLEXPORTAPI
#else
    #define LIB_LIBUICXX_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_METAGEOMS
    #define LIB_METAGEOMS_API DLLEXPORTAPI
#else
    #define LIB_METAGEOMS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_METATOOLS
    #define LIB_METATOOLS_API DLLEXPORTAPI
    #define LIB_METATOOLS_CLASS_API DLLEXPORTAPI
#else
    #define LIB_METATOOLS_API DLLIMPORTAPI
    #define LIB_METATOOLS_CLASS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_NAME_LIST
    #define LIB_NAME_LIST_API DLLEXPORTAPI
#else
    #define LIB_NAME_LIST_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PERSONA
    #define LIB_PERSONA_API DLLEXPORTAPI
#else
    #define LIB_PERSONA_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PGLGRAPHTOOL
    #define LIB_PGLGRAPHTOOL_API DLLEXPORTAPI
#else
    #define LIB_PGLGRAPHTOOL_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PGLPREVIEWKIT
    #define LIB_PGLPREVIEWKIT_API DLLEXPORTAPI
#else
    #define LIB_PGLPREVIEWKIT_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PGLUIKIT
    #define LIB_PGLUIKIT_API DLLEXPORTAPI
#else
    #define LIB_PGLUIKIT_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PR
    #define LIB_PR_API DLLEXPORTAPI
#else
    #define LIB_PR_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PRINTLIB
    #define LIB_PRINTLIB_API DLLEXPORTAPI
#else
    #define LIB_PRINTLIB_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PRO_NET
    #define LIB_PRO_NET_API DLLEXPORTAPI
#else
    #define LIB_PRO_NET_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PROSTANDALONE
    #define LIB_PROSTANDALONE_API DLLEXPORTAPI
#else
    #define LIB_PROSTANDALONE_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PROWTJSCB
    #define LIB_PROWTJSCB_API DLLEXPORTAPI
#else
    #define LIB_PROWTJSCB_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PROWTZBJSCB
    #define LIB_PROWTZBJSCB_API DLLEXPORTAPI
    #define LIB_PROWTZBJSCB_CLASS_API DLLEXPORTAPI
#else
    #define LIB_PROWTZBJSCB_API DLLIMPORTAPI
    #define LIB_PROWTZBJSCB_CLASS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PROWT_CONSOLE_UI
    #define LIB_PROWT_CONSOLE_UI_API DLLEXPORTAPI
#else
    #define LIB_PROWT_CONSOLE_UI_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PROWT_HELPWIN
    #define LIB_PROWT_HELPWIN_API DLLEXPORTAPI
#else
    #define LIB_PROWT_HELPWIN_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PROWT_JS_CALLBACKS
    #define LIB_PROWT_JS_CALLBACKS_API DLLEXPORTAPI
#else
    #define LIB_PROWT_JS_CALLBACKS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PROWT_SERVER_UTILS
    #define LIB_PROWT_SERVER_UTILS_API DLLEXPORTAPI
#else
    #define LIB_PROWT_SERVER_UTILS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PROWT_XML_UGC
    #define LIB_PROWT_XML_UGC_API DLLEXPORTAPI
#else
    #define LIB_PROWT_XML_UGC_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PROWTAPI
    #define LIB_PROWTAPI_API DLLEXPORTAPI
#else
    #define LIB_PROWTAPI_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PROWTCONNECT
    #define LIB_PROWTCONNECT_API DLLEXPORTAPI
#else
    #define LIB_PROWTCONNECT_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PROWTINTF
    #define LIB_PROWTINTF_API DLLEXPORTAPI
#else
    #define LIB_PROWTINTF_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PROWTLINKHANDLERS
    #define LIB_PROWTLINKHANDLERS_API DLLEXPORTAPI
#else
    #define LIB_PROWTLINKHANDLERS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PROWTMSGCMN
    #define LIB_PROWTMSGCMN_API DLLEXPORTAPI
#else
    #define LIB_PROWTMSGCMN_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PROWTPDMACTIONSINTF
    #define LIB_PROWTPDMACTIONSINTF_API DLLEXPORTAPI
#else
    #define LIB_PROWTPDMACTIONSINTF_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PROWTREGXML
    #define LIB_PROWTREGXML_API DLLEXPORTAPI
#else
    #define LIB_PROWTREGXML_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PROWTUIUTIL
    #define LIB_PROWTUIUTIL_API DLLEXPORTAPI
#else
    #define LIB_PROWTUIUTIL_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PROWTUTILSINTF
    #define LIB_PROWTUTILSINTF_API DLLEXPORTAPI
#else
    #define LIB_PROWTUTILSINTF_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PROWTZIP
    #define LIB_PROWTZIP_API DLLEXPORTAPI
#else
    #define LIB_PROWTZIP_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PTCUI_TK
    #define LIB_PTCUI_TK_API DLLEXPORTAPI
#else
    #define LIB_PTCUI_TK_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_QCR_EXAMINE
    #define LIB_QCR_EXAMINE_API DLLEXPORTAPI
#else
    #define LIB_QCR_EXAMINE_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_REFVIEWER
    #define LIB_REFVIEWER_API DLLEXPORTAPI
#else
    #define LIB_REFVIEWER_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_REMBAT_COM
    #define LIB_REMBAT_COM_API DLLEXPORTAPI
#else
    #define LIB_REMBAT_COM_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_REMCLNT
    #define LIB_REMCLNT_API DLLEXPORTAPI
#else
    #define LIB_REMCLNT_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_REMCOMMON
    #define LIB_REMCOMMON_API DLLEXPORTAPI
#else
    #define LIB_REMCOMMON_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_RNDTOOLS
    #define LIB_RNDTOOLS_API DLLEXPORTAPI
#else
    #define LIB_RNDTOOLS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_SECTOOLS
    #define LIB_SECTOOLS_API DLLEXPORTAPI
#else
    #define LIB_SECTOOLS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_SLCC
    #define LIB_SLCC_API DLLEXPORTAPI
#else
    #define LIB_SLCC_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_STACKWALK
    #define LIB_STACKWALK_API DLLEXPORTAPI
#else
    #define LIB_STACKWALK_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_SURFTOOLS
    #define LIB_SURFTOOLS_API DLLEXPORTAPI
#else
    #define LIB_SURFTOOLS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_TMC_DPR_LIBDRM_API
    #define LIB_TMC_DPR_LIBDRM_API_API DLLEXPORTAPI
#else
    #define LIB_TMC_DPR_LIBDRM_API_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_TRNGEXP
    #define LIB_TRNGEXP_API DLLEXPORTAPI
#else
    #define LIB_TRNGEXP_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_U3DCXX
    #define LIB_U3DCXX_API DLLEXPORTAPI
#else
    #define LIB_U3DCXX_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_UFST47
    #define LIB_UFST47_API DLLEXPORTAPI
#else
    #define LIB_UFST47_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_UITOOLS
    #define LIB_UITOOLS_API DLLEXPORTAPI
	#define LIB_UITOOLS_CLASS_API DLLEXPORTAPI
#else
    #define LIB_UITOOLS_API DLLIMPORTAPI
	#define LIB_UITOOLS_CLASS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_UIUDC
    #define LIB_UIUDC_API DLLEXPORTAPI
#else
    #define LIB_UIUDC_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_UI_DIALOG_EDITOR_BASE
    #define LIB_UIDE_BASE_API DLLEXPORTAPI
	#define LIB_UIDE_BASE_CLASS_API DLLEXPORTAPI
#else
    #define LIB_UIDE_BASE_API DLLIMPORTAPI
	#define LIB_UIDE_BASE_CLASS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_CHARTAPP_DLL
    #define LIB_CHARTAPP_DLL_API DLLEXPORTAPI
	#define LIB_CHARTAPP_DLL_CLASS_API DLLEXPORTAPI
#else
    #define LIB_CHARTAPP_DLL_API DLLIMPORTAPI
	#define LIB_CHARTAPP_DLL_CLASS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_UNIFSUTIL
    #define LIB_UNIFSUTIL_API DLLEXPORTAPI
#else
    #define LIB_UNIFSUTIL_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_UNIPDM
    #define LIB_UNIPDM_API DLLEXPORTAPI
#else
    #define LIB_UNIPDM_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_UNITMGR
    #define LIB_UNITMGR_API DLLEXPORTAPI
#else
    #define LIB_UNITMGR_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_UTF8ENC
    #define LIB_UTF8ENC_API DLLEXPORTAPI
#else
    #define LIB_UTF8ENC_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_UWGMCLNTPREFSCHEMA
    #define LIB_UWGMCLNTPREFSCHEMA_API DLLEXPORTAPI
#else
    #define LIB_UWGMCLNTPREFSCHEMA_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_UWGMMSGSYSTEM
    #define LIB_UWGMMSGSYSTEM_API DLLEXPORTAPI
#else
    #define LIB_UWGMMSGSYSTEM_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_UWGMPREFBASE
    #define LIB_UWGMPREFBASE_API DLLEXPORTAPI
#else
    #define LIB_UWGMPREFBASE_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_UWGMPREFMGR
    #define LIB_UWGMPREFMGR_API DLLEXPORTAPI
#else
    #define LIB_UWGMPREFMGR_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_VGI
    #define LIB_VGI_API DLLEXPORTAPI
#else
    #define LIB_VGI_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_XTOPSTUBS
    #define LIB_XTOPSTUBS_API DLLEXPORTAPI
#else
    #define LIB_XTOPSTUBS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_ZBASE_APPS
    #define LIB_ZBASE_APPS_API DLLEXPORTAPI
#else
    #define LIB_ZBASE_APPS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_ZBASEUTILS
    #define LIB_ZBASEUTILS_API DLLEXPORTAPI
#else
    #define LIB_ZBASEUTILS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_THREE_D_INTF
    #define LIB_3D_INTF_API DLLEXPORTAPI
#else
    #define LIB_3D_INTF_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_STEP_INTF
    #define LIB_STEP_INTF_API DLLEXPORTAPI
#else
    #define LIB_STEP_INTF_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PSLD_INTF
    #define LIB_PSLD_INTF_API DLLEXPORTAPI
#else
    #define LIB_PSLD_INTF_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_IGES_INTF
    #define LIB_IGES_INTF_API DLLEXPORTAPI
#else
    #define LIB_IGES_INTF_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_AI_INTF
    #define LIB_AI_INTF_API DLLEXPORTAPI
#else
    #define LIB_AI_INTF_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_PTK_INTF
    #define LIB_PTK_INTF_API DLLEXPORTAPI
#else
    #define LIB_PTK_INTF_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_CATV4_INTF
    #define LIB_CATV4_INTF_API DLLEXPORTAPI
#else
    #define LIB_CATV4_INTF_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_ACIS_INTF
    #define LIB_ACIS_INTF_API DLLEXPORTAPI
#else
    #define LIB_ACIS_INTF_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_NEUT_INTF
    #define LIB_NEUT_INTF_API DLLEXPORTAPI
#else
    #define LIB_NEUT_INTF_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_VDA_INTF
    #define LIB_VDA_INTF_API DLLEXPORTAPI
#else
    #define LIB_VDA_INTF_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_DYNATRACE
    #define LIB_DYNATRACE_API DLLEXPORTAPI
    #define LIB_DYNATRACE_CLASS_API DLLEXPORTAPI
#else
    #define LIB_DYNATRACE_API DLLIMPORTAPI
    #define LIB_DYNATRACE_CLASS_API DLLIMPORTAPI
#endif
#ifdef COMPILING_LIB_ZBUTILS
    #define LIB_ZBUTILS_API DLLEXPORTAPI
    #define LIB_ZBUTILS_CLASS_API DLLEXPORTAPI
#else
    #define LIB_ZBUTILS_API DLLIMPORTAPI
    #define LIB_ZBUTILS_CLASS_API DLLIMPORTAPI
#endif
#else
#define LIB_AIUTILS_API extern
#define LIB_ANALYSISTOOLS_API extern
#define LIB_APPINTF_API extern
#define LIB_CADDSUTILS_API extern
#define LIB_CATPRTTOOLS_API extern
#define LIB_CORESECTOOLS_API extern
#define LIB_CORETOOLS_API extern
#define LIB_COREUTILS_API extern
#define LIB_CREOMDAPI_API extern
#define LIB_CTX_HELP_API extern
#define LIB_DBKEYTOOLS_API extern
#define LIB_DIMTOOLS_API extern
#define LIB_DIMUTILS_API extern
#define LIB_ANNOTTOOLS_API extern
#define LIB_ASM_PREVIEW_API extern
#define LIB_BMXGRAPHTOOL_API extern
#define LIB_CFG_ASM_VERIFY_UI_API extern
#define LIB_DMA_UI_API extern
#define LIB_DRMCLIENT_API extern
#define LIB_ECAD_API extern
#define LIB_EZ_NET_API extern
#define LIB_FEAT_UI_API extern
#define LIB_FEMLIB_API extern
#define LIB_FREEFORM_COMBINED_API extern
#define LIB_GEOMAGIC_API extern
#define LIB_GLOBALMODEL_API extern
#define LIB_GRMANIP_API extern
#define LIB_HELPLIB_API extern
#define LIB_INTFGEOFIX_API extern
#define LIB_LAYOUT_UI_API extern
#define LIB_LEAD_UI_API extern
#define LIB_LIBDCADUI_API extern
#define LIB_LIBSAVEMOD_API extern
#define LIB_LIVE_UI_API extern
#define LIB_MANUFACT_API extern
#define LIB_MFGGEOM_API extern
#define LIB_MOLD_API extern
#define LIB_MTRACK_API extern
#define LIB_TRYOUTFSDRV_API extern
#define LIB_NDPDM_API extern
#define LIB_NDUTIL_API extern
#define LIB_ODUIKIT_API extern
#define LIB_PGLINTF_API extern
#define LIB_PGLSTKIT_API extern
#define LIB_PGLTOOLKIT_API extern
#define LIB_PRO_AD_API extern
#define LIB_PRO_EH_API extern
#define LIB_PRO_IP_API extern
#define LIB_PRO_QZ_API extern
#define LIB_PROD_INTF_API extern
#define LIB_PRODLG_API extern
#define LIB_PRODLG_UI_API extern
#define LIB_PROWT_BASE_BROWSER_API extern
#define LIB_PROWT_MSG_UTILS_API extern
#define LIB_PROWT_OPT_UTILS_API extern
#define LIB_PROWT_SERVER_LOC_REG_API extern
#define LIB_PROWT_SERVER_REGISTRY_API extern
#define LIB_PROWT_UI_API extern
#define LIB_PROWTTOOLS_API extern
#define LIB_RTALOC_API extern
#define LIB_SMM_API extern
#define LIB_SMTDESIGN_API extern
#define LIB_SUBDIVISION_API extern
#define LIB_TMC_DPR_DRM_TOOLS_API extern
#define LIB_TMC_DPR_LIBDRM_PROE_API extern
#define LIB_TOOLKIT_API extern
#define LIB_TOP_API extern
#define LIB_UIHELPERS_API extern
#define LIB_WPPLIBS_API extern
#define LIB_XTOPSTART_API extern
#define LIB_ENTDISPTOOL_API extern
#define LIB_ENTTOOLS_API extern
#define LIB_EZ_EMAIL_API extern
#define LIB_FCLIB_API extern
#define LIB_FEM_NEUTRAL_API extern
#define LIB_FLYBASE_API extern
#define LIB_GPLUGREAD_API extern
#define LIB_GEOMTOOLS_API extern
#define LIB_SOLVERTOOLS_API extern 
#define LIB_HLREXP_API extern
#define LIB_IC_API extern
#define LIB_INTFDRAW_LIB_API extern
#define LIB_INTFDRAWOUT_LIB_API extern
#define LIB_INTFTOOLS_API extern
#define LIB_IPC_COMMS_API extern
#define LIB_JPEGSOURCE_API extern
#define LIB_LI_IPC_API extern
#define LIB_LIBBROWSER_API_API extern
#define LIB_LIBDCADTKCLNT_API extern
#define LIB_LIBDUI_API extern
#define LIB_LIBGRMANIP_API extern
#define LIB_LIBHBSBIND_API extern
#define LIB_LIBPLPF_LOW_API extern
#define LIB_LIBTRLCLNT_API extern
#define LIB_LIBUI_API extern
#define LIB_LIBUICXX_API extern
#define LIB_METAGEOMS_API extern
#define LIB_METATOOLS_API extern
#define LIB_NAME_LIST_API extern
#define LIB_PERSONA_API extern
#define LIB_PGLGRAPHTOOL_API extern
#define LIB_PGLPREVIEWKIT_API extern
#define LIB_PGLUIKIT_API extern
#define LIB_PR_API extern
#define LIB_PRINTLIB_API extern
#define LIB_PRO_NET_API extern
#define LIB_PROSTANDALONE_API extern
#define LIB_PROWTJSCB_API extern
#define LIB_PROWT_CONSOLE_UI_API extern
#define LIB_PROWT_HELPWIN_API extern
#define LIB_PROWT_JS_CALLBACKS_API extern
#define LIB_PROWT_SERVER_UTILS_API extern
#define LIB_PROWT_XML_UGC_API extern
#define LIB_PROWTAPI_API extern
#define LIB_PROWTCONNECT_API extern
#define LIB_PROWTINTF_API extern
#define LIB_PROWTLINKHANDLERS_API extern
#define LIB_PROWTMSGCMN_API extern
#define LIB_PROWTPDMACTIONSINTF_API extern
#define LIB_PROWTREGXML_API extern
#define LIB_PROWTUIUTIL_API extern
#define LIB_PROWTUTILSINTF_API extern
#define LIB_PROWTZIP_API extern
#define LIB_PTCUI_TK_API extern
#define LIB_QCR_EXAMINE_API extern
#define LIB_REFVIEWER_API extern
#define LIB_REMBAT_COM_API extern
#define LIB_REMCLNT_API extern
#define LIB_REMCOMMON_API extern
#define LIB_RNDTOOLS_API extern
#define LIB_SECTOOLS_API extern
#define LIB_SLCC_API extern
#define LIB_STACKWALK_API extern
#define LIB_SURFTOOLS_API extern
#define LIB_TMC_DPR_LIBDRM_API_API extern
#define LIB_TRNGEXP_API extern
#define LIB_U3DCXX_API extern
#define LIB_UFST47_API extern
#define LIB_UITOOLS_API extern
#define LIB_UIUDC_API extern
#define LIB_UNIFSUTIL_API extern
#define LIB_UNIPDM_API extern
#define LIB_UNITMGR_API extern
#define LIB_UTF8ENC_API extern
#define LIB_UWGMCLNTPREFSCHEMA_API extern
#define LIB_UWGMMSGSYSTEM_API extern
#define LIB_UWGMPREFBASE_API extern
#define LIB_UWGMPREFMGR_API extern
#define LIB_VGI_API extern
#define LIB_XTOPSTUBS_API extern
#define LIB_ZBASE_APPS_API extern
#define LIB_ZBASEUTILS_API extern
#define LIB_3D_INTF_API extern
#define LIB_STEP_INTF_API extern
#define LIB_PSLD_INTF_API extern
#define LIB_IGES_INTF_API extern
#define LIB_AI_INTF_API extern
#define LIB_PTK_INTF_API extern
#define LIB_CATV4_INTF_API extern
#define LIB_ACIS_INTF_API extern
#define LIB_NEUT_INTF_API extern
#define LIB_VDA_INTF_API extern
#define LIB_DYNATRACE_API extern
#define LIB_PROWTZBJSCB_API extern
#define LIB_ZBUTILS_API extern
#define LIB_DYNATRACE_CLASS_API 
#define LIB_UITOOLS_CLASS_API 
#define LIB_UIDE_BASE_API extern
#define LIB_UIDE_BASE_CLASS_API
#define LIB_CHARTAPP_DLL_API extern
#define LIB_CHARTAPP_DLL_CLASS_API 
#define LIB_CORETOOLS_CLASS_API
#define LIB_COREUTILS_CLASS_API
#define LIB_METATOOLS_CLASS_API 
#define LIB_IC_CLASS_API
#define LIB_FREEFORM_COMBINED_CLASS_API 
#define LIB_CREOMDAPI_CLASS_API 
#define LIB_PROWT_WPPLIBS_SERVER_LOC_REG_CLASS_API
#define LIB_PROWTZBJSCB_CLASS_API 
#define LIB_ZBUTILS_CLASS_API 
#endif /*DLL_IMPL*/

#endif

