#include <ProToolkit.h>



#ifndef PROTOOLKIT_SECTION_CONSTRAINTS
#define PROTOOLKIT_SECTION_CONSTRAINTS

PRO_BEGIN_C_DECLS

typedef enum
{
  PRO_CONSTRAINT_TYPE_UNKNOWN       = -1 /* a trap for errors */
,  PRO_CONSTRAINT_SAME_POINT         = 0
,  PRO_CONSTRAINT_HORIZONTAL_ENT     = 1
,  PRO_CONSTRAINT_VERTICAL_ENT       = 2
,  PRO_CONSTRAINT_PNT_ON_ENT         = 3
,  PRO_CONSTRAINT_TANGENT_ENTS       = 4
,  PRO_CONSTRAINT_ORTHOG_ENTS        = 5
,  PRO_CONSTRAINT_EQUAL_RADII        = 6
,  PRO_CONSTRAINT_PARALLEL_ENTS      = 7
,  PRO_CONSTRAINT_EQUAL_SEGMENTS     = 8
,  PRO_CONSTRAINT_COLLINEAR_LINES    = 9
,  PRO_CONSTRAINT_SYMMETRY           = 14
,  PRO_CONSTRAINT_SAME_COORD         = 17
,  PRO_CONSTRAINT_SAME_Y_COORD       = 30
,  PRO_CONSTRAINT_SAME_X_COORD       = 31
,  PRO_CONSTRAINT_MIDDLE_POINT       = 35
,  PRO_CONSTRAINT_EQUAL_CURVATURE    = 36

} ProConstraintType;

typedef enum
{
  PRO_TK_CONSTRAINT_DENIED  = 0,
  PRO_TK_CONSTRAINT_ENABLED = 1

} ProConstraintStatus;

PRO_END_C_DECLS

#endif


